TS-29616 Logging of HTTP Status Text
cqse/teamscale-javascript-profiler pull request #1
Opened 2022-03-08 09:15 UTC by stahlbauer

Addresses issue [TS-29616](https://cqse.atlassian.net/browse/TS-29616)

- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.

2022-03-08 10:19 UTC, karottenreibe commented
There's build failures, please have a look :-)

2022-03-08 10:20 UTC, karottenreibe requested changes

2022-03-08 10:20 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +						logger.error(`Upload failed with an error: ${response.statusText}`);
please also include the status code here so both are present in the error message

2022-03-08 10:42 UTC, karottenreibe commented
I just tried to test this log statement to see what is actually logged in the customer's scenario but failed to generate any error log at all:
![image](https://user-images.githubusercontent.com/38839/157221689-d39350e9-08ad-4aad-b622-43a5be09af1e.png)
Same when trying with a totally wrong access key. Can you please check why nothing is logged even when the collector is clearly misconfigured?

2022-03-08 10:49 UTC, karottenreibe commented
OK, I see, I need to also actually send at least one line of coverage to the collector. However, after doing that, I still don't see the error log, only some cryptic stuff:

![image](https://user-images.githubusercontent.com/38839/157223997-fd9dc87b-85dd-4673-9e4f-df43e54272af.png)

2022-03-08 10:50 UTC, karottenreibe commented
Also please note the "undefined" in the first few info logs. We should fix that as well.

2022-03-09 10:15 UTC, karottenreibe requested changes

2022-03-09 10:15 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +							} else if (error.request) {
why not log error.message in this case?

2022-03-09 10:15 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +									logger.error(`Upload failed with code ${response.status}: ${response.statusText}`);
why not log error.message in this case?

2022-03-09 13:39 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/main.ts
> +									logger.error(`Upload failed with code ${response.status}: ${response.statusText}`);
The field might not always be set. See https://axios-http.com/docs/handling_errors for the official Axios error handling proposal.

2022-03-09 13:39 UTC, stahlbauer commented
The build does not yet finish due to a problem with running Cypress within the Github pipeline.

2022-03-09 14:36 UTC, karottenreibe requested changes

2022-03-09 14:36 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +					await this.uploadToToTeamscale(config, logger, coverageFile, lines);
typo in `uploadToToTeamscale`: `ToTo` instead of `To`

2022-03-09 14:36 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +				if (error.message) {
now if error.response == error.request == error.message == null we log nothing. Please add an else clause and just log the entire error object by converting it to JSON as a last resort fallback so we are 100% certain we don't swallow any errors by accident.

2022-03-09 14:36 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/main.ts
> +						logger.error(`Request failed ${response.status} with following response: ${response.data}`);
no need to log response.status twice (the above message already logs it). You could just collapse both log statements into one

2022-03-10 09:56 UTC, merged

2022-03-10 09:56 UTC, karottenreibe commented
Awesome, thanks a lot :-)