TS-35047 One Phase Instrument
cqse/teamscale-javascript-profiler pull request #108
Opened 2023-12-22 08:16 UTC by stahlbauer

Addresses issue [TS-35047](https://cqse.atlassian.net/browse/TS-35047)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2023-12-22 15:24 UTC, DreierF requested changes

2023-12-22 15:24 UTC, DreierF commented on architecture-decisions/one-phase-instrumenter/0005-message-format.md
> +The intervals are inclusive, that is, the `to` element is included---`l1-1` would mean coverage of the first line.
`l1-1` is not very helpful to demonstrate the inclusiveness IMHO because both bounds are equal.

2023-12-22 15:24 UTC, DreierF commented on architecture-decisions/one-phase-instrumenter/0005-message-format.md
> +
Decision is missing

2023-12-22 15:24 UTC, DreierF commented on packages/lib-instrument/src/instrumenter.ts
> -            cb(filename, output.sourceMappingURL as string);
Does this mean that we currently don't create a sourcemap from the instrumented bundle back to the original code? We should add this to the known issues/limitations as this might be an issue in certain environments i.e. when the SuT is deployed with intrumentation but the team still wants to be able to investigate JS errors during the test.

2023-12-22 15:24 UTC, DreierF commented on packages/lib-instrument/test/util/verifier.ts
> +}
Would this work as well?

```suggestion
var UNIVERSE = globalThis;
```

2024-01-09 11:22 UTC, DreierF requested changes

2024-01-09 11:22 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/worker/Countdown.ts
> +    // eslint-disable-next-line no-useless-constructor
There seems to be some misconfiguration in ESLint. The rule should be disabled and instead the version from [typescript-eslint](https://typescript-eslint.io/rules/no-useless-constructor/) should be enabled. This should happen automatically AFAIU when applying the recommended rules (see https://typescript-eslint.io/rules/no-useless-constructor/)

2024-01-09 11:22 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/worker/CoverageAggregator.ts
> +			fileCoverage.push(this.arrayToLineColCov('f', ranges.functions));
Do we actually need/use the branch, statement and function infos?

2024-01-09 11:22 UTC, DreierF commented on test/systemtest.mjs
> +			'src/app/heroes/heroes.component.ts': [12, 22, 35, 36],
How can those changes be explained?

2024-01-10 10:17 UTC, stahlbauer commented on packages/lib-instrument/test/util/verifier.ts
> +}
Good point. Yes, this should also work.

2024-01-10 10:26 UTC, stahlbauer commented on packages/lib-instrument/test/varia.test.ts
> -        const v = create('output = args[0];', { file: 'c:\\x\\y.js' });
Because we removed the `file` parameter completely.

2024-01-10 10:30 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
> -			if (messageType.startsWith(ProtocolMessageTypes.TYPE_SOURCEMAP)) {
Good idea.

2024-01-10 10:48 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +				const isToCover = sourcePattern.isAnyIncluded([originLocation.filename]);
Simplified this.

2024-01-10 11:57 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
> +					session.putLineCoverage(filename, range[0], range[2]);
Good catch. This was the only place I tried using generated code and it does not really reflect the requirements :-D

2024-01-10 13:15 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +		console.log("Should", loc);
A leftover. Removed.

2024-01-10 17:11 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/vaccine/worker/CoverageAggregator.ts
> +			fileCoverage.push(this.arrayToLineColCov('f', ranges.functions));
Removed all non-line-coverage functionality.

2024-01-10 17:13 UTC, stahlbauer commented on test/systemtest.mjs
> +			'src/app/heroes/heroes.component.ts': [12, 22, 35, 36],
For me this was fine since line 11 only describes the definition of the class `export class HeroesComponent implements OnInit {` and coverage for this line is not really expected or of value, is it?

2024-01-11 15:00 UTC, DreierF requested changes

2024-01-11 15:00 UTC, DreierF commented on packages/lib-instrument/test/util/verifier.ts
> +        for (const coverageType of ['lines']) {
This seems overly complex for accessing a single property. We could either make `CoveragePerLine(AndType)` a `Record<string, number>` or even just a `Record<string, boolean>`?

2024-01-11 15:00 UTC, DreierF commented on packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
> +				if (range.length === 2) {
I don't get how the parsing currently works 🤔 

We split the by lines and for each line that starts with `@` (which should be all lines) we extract the filename and ignore the rest of the line. Am I missing something or is the example not fitting to the implemented parsing approach?

In case this is really broken ATM, why does none of our tests catch this?

2024-01-11 15:00 UTC, DreierF commented on packages/teamscale-coverage-collector/test/CollectorClient.ts
> +		socket.send(`c @${fileName};${startLine}-${endLine}`);
Do we really want to send the file name for each range? Sounds very expensive

2024-01-11 15:00 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/worker/Countdown.ts
> -    // eslint-disable-next-line no-useless-constructor
So there was no ESLint change needed? Was this a leftover that did no longer produce an error? In that case it might make sense to enable ESLint's `reportUnusedDisableDirectives` option

2024-01-11 15:03 UTC, DreierF commented on packages/teamscale-coverage-collector/test/CollectorClient.ts
> +		socket.send(`c @${fileName};${startLine}-${endLine}`);
💡

2024-01-11 15:43 UTC, stahlbauer commented on packages/lib-instrument/test/util/verifier.ts
> +        for (const coverageType of ['lines']) {
Good catch. This part was generally a bit error prone.

2024-01-11 15:46 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
> +				if (range.length === 2) {
This is not broken. This models a state machine. The input is split into tokens; newline, and semikolons divide tokens. One range is a token. 

Added one more comment.

2024-01-11 15:48 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
> +				if (range.length === 2) {
We can also have a separate Meet to discuss this.

2024-01-11 15:48 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/vaccine/worker/Countdown.ts
> -    // eslint-disable-next-line no-useless-constructor
It was a useless leftover, yes.

2024-01-11 17:01 UTC, merged