TS-37604 Made the line coverage collection less memory intense
cqse/teamscale-javascript-profiler pull request #129
Opened 2024-02-15 13:28 UTC by stahlbauer

Addresses issue [TS-37604](https://cqse.atlassian.net/browse/TS-37604)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2024-02-15 14:39 UTC, DreierF requested changes

2024-02-15 14:39 UTC, DreierF commented on packages/lib-instrument/src/visitor.ts
> +    }
I would have a tendency to reverse the logic to:
```suggestion
    let argumentList = [
        { type: 'Identifier', name: originFileId } as Identifier,
        { type: 'NumericLiteral', value: range.start.line } as NumericLiteral
    ];

    // Only pass end line argument if they are different.
    // See also https://v8.dev/blog/adaptor-frame for performance considerations
    if (range.start.line !== range.end.line) {
        argumentList.push({ type: 'NumericLiteral', value: range.end.line } as NumericLiteral)
    }
```

2024-02-15 14:39 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/buffer.ts
> +    function putLineCoverage(fileId: string, startLine: number, endLine?: number): void {
Not 100% sure, but this should also work:

```suggestion
    function putLineCoverage(fileId: string, startLine: number, endLine = startLine): void {
```

2024-02-15 14:39 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/buffer.ts
> +        if (bufferedLines.size > 1000) {
Wouldn't this cause coverage to take very long to get to the collector, when not much is happening on the page? Not sure how big of a problem that is in practice, but it looks like a tripping hazard to me.

2024-02-16 08:58 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/vaccine/buffer.ts
> +        if (bufferedLines.size > 1000) {
There is an additional timer. So this is only to make sure that the buffer does not get too filled.

2024-02-16 08:58 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/vaccine/buffer.ts
> +        if (bufferedLines.size > 1000) {
Changed it to 100

2024-02-16 08:58 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/vaccine/buffer.ts
> +        if (bufferedLines.size > 1000) {
💡

2024-02-16 12:06 UTC, merged