TS-37640 Sparse dumping of infos
cqse/teamscale-javascript-profiler pull request #134
Opened 2024-02-20 16:58 UTC by stahlbauer

Addresses issue [TS-37640](https://cqse.atlassian.net/browse/TS-37640)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2024-02-20 18:16 UTC, DreierF requested changes

2024-02-20 19:21 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/App.ts
> +				}
Should work.

2024-02-20 19:25 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
Both debug and info have too much overlap with the debug levels. But enable debug will produce way more data. In the case where the collector is started in a separate docker container, getting the infos on dumped coverage is desirable---at least in the setting of some of our bigger users.

2024-02-20 19:29 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
Having a default `true` here is odd, yes.

2024-02-20 19:30 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
For now, I would propose to make it `false` by default, that is produce messages whenever coverage is dumped.

2024-02-21 06:45 UTC, DreierF commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
This still doe IMHO not resolve the naming issue. `dump-silently` is confusing. I'd accept `silent` as this is something people will recognize from other tools.

2024-02-21 07:43 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
The current semantics do not match `--silent` in the traditional sense: some output is produced; only a part of the functionality is silenced. What about `--silent-dump`?

2024-02-21 08:42 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
The desired default behavior might depend on the use cases: Collecting coverage of manual tests, collecting coverage from tests executed within a given CI/CD pipeline.

2024-02-21 08:52 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
IMO we should not introduce a flag to toggle specific log output at all that is orthogonal to the log levels. It's confusing because if you set the log level to WARN but also enable these messages via this flag: will the output then be shown or filtered? It remains unclear and is unnecessarily complicated IMO.

Can we instead create a special log level that is between debug and info to log these statistics? Then users can enable this level to get these messages but not debug messages?

Or is this functionality specifically for debugging problems with the collector? Then I would say: just make it debug output. You're not supposed to have that on all the time anyways and filtering the debug log for these statistics is easy with grep. So for the one-time problem debugging use-case I find enabling debug logging totally OK.

2024-02-21 08:53 UTC, karottenreibe commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
Also: if you want input from me on GitHub, please ping me on Slack as well since I get so many GitHub mails, I mostly just archive them without reading if I'm not a reviewer or implementor of the PR. So I only read this one "by accident" ;-)

2024-02-21 09:54 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
Using the log levels here in a more consistent way would be an option. We could change the existing DEBUG statements to TRACE, and use DEBUG here.

2024-02-21 10:35 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
I have removed the configuration parameter now in favor of the DEBUG log level; existing debug statements do now have level TRACE.

2024-02-21 10:35 UTC, stahlbauer commented on packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
> +		default: true});
Thanks for this fruitful discussion :) I think we can up with a clean solution.

2024-02-21 11:50 UTC, merged