Cr/32321 Profiler Benchmarking Infrastructure
cqse/teamscale-javascript-profiler pull request #31
Opened 2022-12-01 12:46 UTC by stahlbauer

Addresses issue [TS-32321](https://cqse.atlassian.net/browse/TS-32321)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2023-01-04 15:55 UTC, AnonymFx reviewed
Meta points (additionally, please check comments in the code):
* Is there any specific reason why `profile_testing.sh` and `profile_instrumentation.sh` are bash files? Wouldn't it be easier to do everything in js? Esp. we could omit the writing and pasing of JSON files from/to disk.
* Currently, performance and functional system tests are intermingled with each other. Currently, that's probably the most efficient way to do it in terms of test runtime. Nevertheless, that might not be the best way going forward, imo.

2023-01-04 15:55 UTC, AnonymFx commented on test/systemtest.mjs
> +const perfMeasuresByStudy = {};
I find this kind of lost here in between functions. Imo, it would be better to declare it above the root level for loop at the bottom and maybe even pass it to the functions which need it to make that dependency more explicit.

2023-01-13 15:08 UTC, stahlbauer commented on test/scripts/profile_testing.sh
> +START_NANOS=$(date +%s%N)
For now, I would propose to use `gdate` and provide a helpful error message in case of its absence.

2023-01-13 15:17 UTC, stahlbauer commented on test/scripts/profile_testing.sh
> +PEAK_MEM_MB=$(sed 1d $MEMORY_SAMPLING_FILE | cut -f3 -d" " | sort -n | tail -n1)
Good catch.

2023-01-13 15:39 UTC, stahlbauer commented on test/systemtest.mjs
> +		buildStudy(study);
Good point. I have extracted most of the complex logic from the loop.

2023-01-13 15:39 UTC, stahlbauer commented on test/scripts/profile_instrumentation.sh
> +PEAK_MEM_MB=$(sed 1d $MEMORY_SAMPLING_FILE | cut -f3 -d" " | sort -n | tail -n1)
Fixed.

2023-01-13 15:40 UTC, stahlbauer commented on test/scripts/profile_instrumentation.sh
> +START_NANOS=$(date +%s%N)
Handling this situation now.

2023-01-13 16:06 UTC, stahlbauer commented on test/systemtest.mjs
> +const perfMeasuresByStudy = {};
Good point. Adjusted.

2023-01-13 16:10 UTC, stahlbauer commented on test/systemtest.mjs
> +			const maxNormTimeFraction = study['maxNormTimeFraction'];
Fixed.

2023-01-13 16:11 UTC, stahlbauer commented on test/systemtest.mjs
> +		if ('maxNormTimeFraction' in study) {
Why not? Currently, all studies have filled the field, however, it would be an optional one ;)

2023-01-13 16:12 UTC, stahlbauer commented on test/systemtest.mjs
> +		const study = caseStudies[i+1];
For now, I would keep it that way. The alternative solution would also need some sort of handling.

2023-01-13 16:15 UTC, stahlbauer commented on test/systemtest.mjs
> +		if ('maxNormTimeFraction' in study) {
> Meta points (additionally, please check comments in the code):
> 
> * Is there any specific reason why `profile_testing.sh` and `profile_instrumentation.sh` are bash files? Wouldn't it be easier to do everything in js? Esp. we could omit the writing and pasing of JSON files from/to disk.
> * Currently, performance and functional system tests are intermingled with each other. Currently, that's probably the most efficient way to do it in terms of test runtime. Nevertheless, that might not be the best way going forward, imo.

From my perspective, each performance test also requires making sure that we compare the same things, that is, with the same functionality. From that perspective, the combination makes sense. 

In case this combination gets a problem, we can separate those.

2023-01-13 16:17 UTC, stahlbauer commented on test/systemtest.mjs
> +		if ('maxNormTimeFraction' in study) {
Regarding the Bash scripts: We can create a separate ticket for that. However, I tried the pure JS solution first, and decided to go with the bash solution since it was the more pragmatic way of doing it.

2023-01-19 10:29 UTC, AnonymFx requested changes
Nice, thanks for all the great refactorings, the code is now much easier to read :) 
Also, it's running on MacOS now 🥳
Some smaller comments inline. Also, the GitHub pipeline is failing. I think the `normMemoryFraction` is too high for all studies now that we actually measure memory (except angular because the max is 20 already) 🙈 

Locally, I actually get a different error: 
```
Covered lines are missing! angular-hero-app { 'src/app/heroes/heroes.component.ts': Set(1) { 12 } }
```
Not sure whether that's a setup problem on my end or something else. Do you have an idea?

2023-01-19 10:29 UTC, AnonymFx commented on .github/workflows/build-and-test.yml
> +        run: pip3 install memory-profiler
https://cqse.atlassian.net/browse/TS-33065

2023-01-19 14:41 UTC, stahlbauer commented on test/scripts/common.sh.inc
> +        # Typically available on MacOs (to be installed via homebrew)
We will address this in TS-33077.

2023-01-19 14:42 UTC, stahlbauer commented on test/scripts/common.sh.inc
> +        echo "Please make sure to have a variant of 'date' installed for use in 'bash'".
We will address this in TS-33077.

2023-01-19 14:44 UTC, stahlbauer commented on test/systemtest.mjs
> +		maxNormMemoryFraction: 20.0
Correct. It is already planed to be addressed in that ticket.

2023-01-19 14:48 UTC, stahlbauer commented
> ```
> Covered lines are missing! angular-hero-app { 'src/app/heroes/heroes.component.ts': Set(1) { 12 } }
> ```

It is independent of this ticket. I would consider it to be a flaky test for now. In case the problem persists and you can reproduce it locally: Feel free to create a ticket.

2023-01-24 14:56 UTC, AnonymFx requested changes
I reran the test and it was successful which supports your “it’s flaky” assessment  

Left one more comment inline.

2023-01-24 14:56 UTC, AnonymFx commented on test/systemtest.mjs
> +	const computeStats = (perfType, noInstPerfValue, withInstPerfValue, basePerfValue, fractionFactor) => {
It seems that you wanted to define some functions here that belong together and should not be visible to the rest of the systemtest file. If we'd refactor them to a separate class/file/module (whatever the right term for JS is), we'd achieve the same + 
* We'd remove many of the (mostly valid) Teamscale findings (including method length + reduce file size)
* `summarizePerformanceMeasures(...)` would be a lot easier to understand because you don't have to go through several function definitions and find out what is called when in the end

I don't think it's much effort to do so and imo it's worth the refactoring. I don't expect a perfectly designed interface for the new class/file/module, refactoring these methods with the needed parameters is perfectly fine. 

That means I also disagree with https://cqse.atlassian.net/browse/TS-32321?focusedCommentId=191476 (at least for some of the findings), as we still need to maintain this code and making it easier to understand for new people should be worth it.

2023-01-24 15:11 UTC, stahlbauer commented on test/systemtest.mjs
> +	const computeStats = (perfType, noInstPerfValue, withInstPerfValue, basePerfValue, fractionFactor) => {
I would propose to create a maintenance ticket with priority HIGH for this. Otherwise, tickets waiting for this are blocked further.

2023-01-24 15:11 UTC, stahlbauer commented on test/systemtest.mjs
> +	const computeStats = (perfType, noInstPerfValue, withInstPerfValue, basePerfValue, fractionFactor) => {
@AnonymFx Would this be fine for you?

2023-01-24 16:57 UTC, merged