TS-33912 Support For Profiling Gwt Applications
cqse/teamscale-javascript-profiler pull request #43
Opened 2023-03-29 15:41 UTC by stahlbauer

Addresses issue [TS-33912](https://cqse.atlassian.net/browse/TS-33912)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2023-08-10 14:40 UTC, AnonymFx requested changes

2023-08-10 14:40 UTC, AnonymFx commented on packages/teamscale-javascript-instrumenter/test/unit/FileSystem.test.ts
> +	const folders = findSubFolders('../../test/casestudies/gwt-showcase-js/', 'symbolMaps');
`gwt-showcase-js` doesn't exist anymore (removed with the latest commit) => All new tests (incl. the ones in `WebToolkit.test.ts`) fail.

2023-08-11 11:02 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/WebToolkit.ts
> + * do have the actual application code as arguments.
Thanks. Added.

2023-08-11 11:03 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/WebToolkit.ts
> +			return { codeArguments: [codeArgument], functionName: qualifiedFunctionName, codeAsArrayArgument: true };
I would prefer to not change this for now until we know for sure that there are no code arrays generated by GWT with more than one element.

2023-08-11 11:04 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/WebToolkit.ts
> +			return { codeArguments: [codeArgument], functionName: qualifiedFunctionName, codeAsArrayArgument: true };
(This would be a larger change; for now we would also evaluate whether the profiler is applicable for the pilot customers.)

2023-08-11 11:06 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
>  		// We skip files that we have already instrumented
Good catch.

2023-08-11 11:23 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/test/unit/FileSystem.test.ts
> +	const folders = findSubFolders('../../test/casestudies/gwt-showcase-js/', 'symbolMaps');
Thanks for the pointer. I have added a reduced version of the case study.

2023-08-11 11:52 UTC, stahlbauer commented
Currently we do not have an automated e2e test for the GWT instrumentation. I would address this in a maintenance ticket in a next step. Likely by deploying one of the GWT sample applications in a local Jetty server and collecting coverage from it.

2023-08-11 12:02 UTC, stahlbauer commented
I have looked into the Teamscale findings. These are tollerable for now. However, I would move the source map logic to a separate module after we decide to keep the GWT support.

2023-08-11 12:04 UTC, stahlbauer commented
If possible, I would merge the functionality to the `main` branch to avoid having maintaining several branches in parallel. Furthermore, some of the adjustments made will also benefit the overall JS profiler performance and architecture.

2023-08-16 13:35 UTC, merged