TS-29789 Include/excludes not considered correctly.
cqse/teamscale-javascript-profiler pull request #7
Opened 2022-03-24 14:49 UTC by stahlbauer

Addresses issue [TS-29789](https://cqse.atlassian.net/browse/TS-29789)

- [ ] Changes are tested adequately
- [ ] CHANGELOG.md of the affected packages are updated

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.

2022-03-28 10:07 UTC, DreierF requested changes

2022-03-28 10:07 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +				).then(instrumentedSource => {
Why was this moved into a `then`? As the method is already `async` using `await` instead would be more readable

2022-03-28 10:07 UTC, DreierF commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +		).then((instrumentedSourceMapConsumer: SourceMapConsumer | undefined) => {
Same here

2022-03-29 09:20 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +		).then((instrumentedSourceMapConsumer: SourceMapConsumer | undefined) => {
I have reverted this to async/await.

2022-03-29 09:20 UTC, stahlbauer commented on packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
> +				).then(instrumentedSource => {
I have reverted this to async/await.

2022-03-29 09:30 UTC, merged