Docker systemtest
cqse/teamscale-javascript-profiler pull request #70
Opened 2023-08-25 08:43 UTC by jveihelmann

Addresses issue [TS-33729](https://cqse.atlassian.net/browse/TS-33729)

- [ ] No findings in [Teamscale](https://demo.teamscale.com/activity.html#/teamscale-javascript-profiler/) (c.f. vote of the Teamscale Bot). Flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.
- [ ] Changes are tested adequately
- [ ] Profilers's README.md and the Teamscale documentation are updated in case of user-visible changes
- [ ] CHANGELOG.md of the affected packages are updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

2023-09-11 09:16 UTC, stahlbauer requested changes

2023-09-11 09:16 UTC, stahlbauer commented on docker-compose.yml
> +version: "3.9"
I would prefer to have a file name that indicates the role of use in system tests, `systemtest.dockerfile`?

2023-09-11 09:16 UTC, stahlbauer commented on package.json
> +    "systemtest_release": "pnpm build && node ./test/systemtest.mjs release",
It would be great if we could use colons for naming/grouping related tasks. See, for example, https://corgibytes.com/blog/2017/04/18/npm-tips/

2023-09-11 09:16 UTC, stahlbauer commented on test/scripts/profile_testing.sh
What about having a separate `grafana_testing.sh` file that imports common functionality using a `source`?

2023-09-11 09:16 UTC, stahlbauer commented on test/scripts/profile_testing.sh
Part of the case study definition could then be the script to execute, or it could be determined automatically in case the script name somehow matches the name of the case study.

2023-09-11 09:16 UTC, stahlbauer commented on test/systemtest.mjs
> +				buildGrafana(study);
Maybe we should have separate build scripts? A generic one and scripts to overwrite the behavior for particular case studies?

2023-09-18 09:56 UTC, jveihelmann commented on test/systemtest.mjs
> +				buildGrafana(study);
I think adding a separate build scripts would (at the moment) incrase complexity that is not really needed. At the moment that would result in 2 new files with 3 loc each if I understand this correctly. 

I would suggest keeping it as is and updating this logic if the amount of "release casestudies" grows. WDYT?

2023-09-18 13:33 UTC, stahlbauer requested changes

2023-09-18 13:33 UTC, stahlbauer commented on test/scripts/common.sh.inc
For which reason is this file empty?

2023-09-18 13:33 UTC, stahlbauer commented on test/scripts/grafana_profile_testing.sh
> +
Blank line not needed (one is sufficient).

2023-09-18 13:33 UTC, stahlbauer commented on test/systemtest.mjs
> +				buildGrafana(study);
Generally fine for me.

2023-09-19 06:30 UTC, jveihelmann commented on test/scripts/common.sh.inc
This had to do with permissions beeing wrongly set. Reverted

2023-09-19 06:53 UTC, merged